version: '3.9'

networks:
  my_bridge:
    driver: bridge
    name: my_bridge

services:

  database:
    container_name: database
    image: mongo
    networks:
      - my_bridge

  database_filler:
    container_name: database_filler
    build: database_filler/
    command: python /scripts/filler.py
    volumes:
      - ./data/:/data
    networks:
      - my_bridge
    depends_on:
      - database

  server:
    container_name: server
    build: server/
    ports:
      - "10121:8000"
    command: python /scripts/server.py
    networks:
      - my_bridge
    volumes:
      - content-volume:/scripts/static/content
      - models-volume:/scripts/static/models

  pipeline:
    container_name: pipeline
    build: pipeline/
    ports:
      - "10122:8080"
    command: >
      bash -c "airflow standalone 
      && airflow dags unpause dmls"
    networks:      
      - my_bridge
    volumes:
      - content-volume:/opt/content
      - models-volume:/opt/models
      - ./data/:/opt/data_backup

volumes:
  content-volume:
  models-volume:
